#!/bin/bash
# Launch Dingtalk with Wayland screen share hook
export QT_QPA_PLATFORM="wayland;xcb"
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export LD_PRELOAD="/usr/lib/dingtalk/libdingtalk_hook.so"
cd /opt/dingtalk/release
exec ./com.alibabainc.dingtalk "$@"
